USE [master]
GO

/****** Object:  Database [sportik]    Script Date: 27.05.2023 8:30:05 ******/
CREATE DATABASE [sportik]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sportik', FILENAME = N'D:\Новая папка\MSSQL16.MSSQLSERVER\MSSQL\DATA\sportik.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sportik_log', FILENAME = N'D:\Новая папка\MSSQL16.MSSQLSERVER\MSSQL\DATA\sportik_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sportik].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sportik] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sportik] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sportik] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sportik] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sportik] SET ARITHABORT OFF 
GO

ALTER DATABASE [sportik] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sportik] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sportik] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sportik] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sportik] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sportik] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sportik] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sportik] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sportik] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sportik] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sportik] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sportik] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sportik] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sportik] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sportik] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sportik] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sportik] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sportik] SET RECOVERY FULL 
GO

ALTER DATABASE [sportik] SET  MULTI_USER 
GO

ALTER DATABASE [sportik] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sportik] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sportik] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sportik] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sportik] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sportik] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sportik] SET QUERY_STORE = ON
GO

ALTER DATABASE [sportik] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sportik] SET  READ_WRITE 
GO

